version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/royalgames-server"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/royalgames-client"
    schedule:
      interval: "daily"
