services:
- type: web
  name: royal-games-social-casino
  env: node
  buildCommand: npm run install && npm run client:build && npm run server:build
  startCommand: npm run start
 envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 10000
  - key: HOST
    value: royalgames.onrender.com
  - key: SOCKET_URL
    value: https://royalgames.onrender.com