services:
- type: web
  name: royal-games-social-casino
  env: node
  buildCommand: cd client && npm install && npm run build && cd ../server && npm install && npm start
  startCommand: cd client && npm install && npm start && cd ../server && npm install && npm start
 envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 10000
  - key: HOST
    value: royalgames.onrender.com
  - key: SOCKET_URL
    value: https://royalgames.onrender.com